First caroussel
deltahacks/new-landing pull request #14
Opened 2022-11-11 22:24 UTC by fvcci

2022-11-14 23:41 UTC, KaiKitJeffreyChan approved these changes
very clean code poggers

2022-11-15 18:14 UTC, Krish120003 requested changes

2022-11-15 18:14 UTC, Krish120003 commented on src/components/carrousel/Caroussel.tsx
> +  // TODO put title and descriptions in an object and iterate through that
Is this still a TODO?

2022-11-15 18:14 UTC, Krish120003 commented on src/components/carrousel/Caroussel.tsx
> +  const carroussel = [
Spelled wrong, did you mean carrousel?

2022-11-15 18:14 UTC, Krish120003 commented on src/components/carrousel/CarousselPane.tsx
> +export const mod = (k: number, n: number): number => {
This should be moved to a util file or something since its being imported elsewhere

2022-11-15 18:14 UTC, Krish120003 commented on src/components/carrousel/CarousselPane.tsx
> +const CarousselPane = ({ children, id, numPanes, activePane }: Props) => {
Spelling

2022-11-17 07:54 UTC, Krish120003 commented
Closing in favour of #17 which includes this + requested changes (not checked)

2022-11-17 07:54 UTC, closed without merging